# Generated by Django 5.1 on 2024-08-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='hu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rnr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
